### ISSUE TITLE
Crash when launching with special locale

### ISSUE THREAD

**Issue by BersisSe** [philoufilou/Logic-Chips#5]
Exception message: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: logicchips:ch\u0131p

thats the error I dont know anything about java so I can't really fix it

**Comment by ZZZank** [comment]
This look like a minor typo, please send `latest.log` so that I can locate it easier. 

Also, will this error crash the whole game?

**Comment by BersisSe** [comment]
yeah it crashes the whole game I found this error on the crash report 
here is the log file
[latest.log](https://github.com/user-attachments/files/16394562/latest.log)

**Comment by ZZZank** [comment]
It seems that `ch\u0131p` is produced by translating `CHIP` into lower case, which is absurd, because `I` become `\u0131`(`ı`) instead of normal `i` . 

I've pushed a commit trying to fix this, you can test it via artifacts produced by Github Action, https://github.com/philoufilou/Logic-Chips/actions/runs/10120538639
<img width="683" alt="Snipaste_2024-07-27_11-36-08" src="https://github.com/user-attachments/assets/092c9476-a024-40da-9521-75b8e921e555">
There're many files in it, but you only need to test `forge/build/libs/logicchips-1.20.1-2.1.0-forge.jar` .

**Comment by BersisSe** [comment]
I tested it and still got a error:


Logic Chips (logicchips) has failed to load correctly
java.lang.ExceptionInInitializerError: null
Exception message: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: logicchips:ch\u0131p


here is the latest.log if you want to look at it
[latest.log](https://github.com/user-attachments/files/16398796/latest.log)
there is also the crash report that I found the error in
[crash-2024-07-26_16.09.19-fml.txt](https://github.com/user-attachments/files/16398798/crash-2024-07-26_16.09.19-fml.txt)

**Comment by ZZZank** [comment]
Unfortunately I'm unable to reproduce this, it can be some mods messing with registry, or the language you're using mapped `I` to another letter, or even java problem, but none of these is happening on my side. 
![image](https://github.com/user-attachments/assets/1aea7cca-2096-4304-b002-f0f9cd50fcf6)

you can try artifacts from [this action](https://github.com/philoufilou/Logic-Chips/actions/runs/10155752484), and if possible, please test it with a mininal modlist(fewest required mods).

**Comment by ZZZank** [comment]
Hi, it has been two weeks, have you tried the artifacts mentioned in my last comment?


The artifact mentioned in my last comment: 
> you can try artifacts from [this action](https://github.com/philoufilou/Logic-Chips/actions/runs/10155752484),

**Comment by BersisSe** [comment]
I tried the a**rtifact** without any mods this time, and it works! I also tried deleting the logic chips mod from the modpack, but it still didn't work, so it wasn't the logic chips' fault in the first place. The modpack still doesn't work, but at least one mod is cleared now. Thank you for your assistance.

**Comment by ZZZank** [comment]
👍，I will release a new version soon

**Comment by ZZZank** [comment]
2.1.3 is released: https://www.curseforge.com/minecraft/mc-mods/logic-chips/files/5614659
